#!/usr/bin/env bash
set -euo pipefail

# Frozen training command
/home/yclcg/miniconda3/envs/transshield/bin/python /home/yclcg/DynamicViT_exp_square/main.py --model deit-s --data_set image_folder --data_path /home/yclcg/DynamicViT_exp_square/data/pneumoniamnist_imagefolder_subset/train --eval_data_path /home/yclcg/DynamicViT_exp_square/data/pneumoniamnist_imagefolder_subset/val --nb_classes 2 --output_dir /home/yclcg/DynamicViT_exp_square/outputs/pneumonia_transshield_peproj_zero_fixstep0_lr1e5_actlr10_learnquadgelu_noamp_evalon_epoch8 --log_dir /home/yclcg/DynamicViT_exp_square/outputs/pneumonia_transshield_peproj_zero_fixstep0_lr1e5_actlr10_learnquadgelu_noamp_evalon_epoch8/tb --input_size 224 --batch_size 32 --epochs 8 --num_workers 4 --base_rate 0.7 --ratio_weight 2.0 --lr 1e-5 --warmup_epochs 0 --warmup_steps 50 --clip_grad 1.0 --device cuda --model_ema false --save_ckpt true --save_ckpt_freq 1 --save_ckpt_num 2 --auto_resume false --use_amp false --mixup 0 --cutmix 0 --seed 0 --lr_scale 1.0 --groupa_lr_scale 0.1 --activation_lr_scale 10.0 --cls_distill_weight 1.0 --token_distill_weight 0.02 --use_square_gelu true --square_activation_mode learnable_quadratic_gelu_init --use_approx_attn false --use_mask_pruning true --debug_nan true --patch_embed_bias_init_mode zero --freeze_patch_embed_proj true --pretrained_fix_step 0

# Frozen eval-threshold command
/home/yclcg/miniconda3/envs/transshield/bin/python /home/yclcg/DynamicViT_exp_square/main.py --model deit-s --data_set image_folder --data_path /home/yclcg/DynamicViT_exp_square/data/pneumoniamnist_imagefolder_subset/train --eval_data_path /home/yclcg/DynamicViT_exp_square/data/pneumoniamnist_imagefolder_subset/val --nb_classes 2 --output_dir /home/yclcg/DynamicViT_exp_square/outputs/pneumonia_transshield_peproj_zero_fixstep0_lr1e5_actlr10_learnquadgelu_noamp_evalon_epoch8_threshold_eval --input_size 224 --batch_size 32 --epochs 8 --num_workers 4 --base_rate 0.7 --ratio_weight 2.0 --lr 1e-5 --warmup_epochs 0 --warmup_steps 50 --clip_grad 1.0 --device cuda --model_ema false --save_ckpt false --auto_resume false --use_amp false --mixup 0 --cutmix 0 --seed 0 --lr_scale 1.0 --groupa_lr_scale 0.1 --activation_lr_scale 10.0 --cls_distill_weight 1.0 --token_distill_weight 0.02 --use_square_gelu true --square_activation_mode learnable_quadratic_gelu_init --use_approx_attn false --use_mask_pruning true --patch_embed_bias_init_mode zero --freeze_patch_embed_proj true --pretrained_fix_step 0 --eval true --eval_binary_threshold 0.524941 --resume /home/yclcg/DynamicViT_exp_square/outputs/pneumonia_transshield_peproj_zero_fixstep0_lr1e5_actlr10_learnquadgelu_noamp_evalon_epoch8/checkpoint-best.pth

