load("@rules_python//python:defs.bzl", "py_binary")

package(default_visibility = ["//visibility:public"])

py_binary(
    name = "transshield_network_kth_bridge",
    srcs = ["transshield_network_kth_bridge.py"],
    data = ["//examples/python/conf"],
    deps = [
        "//spu/utils:distributed",
    ],
)
